# Generated by Django 6.1 on 2026-09-01 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_curso_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='slug',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('professor', models.CharField(blank=True, max_length=150)),
                ('semestre', models.CharField(blank=True, max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('trabalho', 'Trabalho'), ('prova', 'Prova'), ('exercicio', 'Exercício'), ('seminario', 'Seminário'), ('projeto', 'Projeto'), ('complementar', 'Atividade complementar'), ('outros', 'Outros')], default='outros', max_length=20)),
                ('prazo', models.DateTimeField()),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em andamento'), ('concluida', 'Concluída'), ('atrasada', 'Atrasada')], default='pendente', max_length=15)),
                ('observacoes', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='core.disciplina')),
            ],
            options={
                'ordering': ['prazo'],
            },
        ),
    ]
