# Generated by Django 6.1 on 2026-09-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_curso_slug_disciplina_atividade'),
        ('core', '0003_alter_curso_slug_disciplina_atividade_and_more'),
    ]

    operations = [
    ]
