# Generated by Django 6.1 on 2026-09-07 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_merge_20260907_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='modulo_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='modulo_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
