# Generated by Django 6.1 on 2026-09-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_atividade_modulo_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='feitos',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
