# Generated by Django 6.1 on 2026-09-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_projeto_feitos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='progresso',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
