# Generated by Django 6.1 on 2026-09-17 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_projeto_progresso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='integrantes',
        ),
    ]
