# Generated by Django 6.1 on 2026-09-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_projeto_integrantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacaoprojeto',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
    ]
