# Generated by Django 6.1 on 2026-10-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_participacaoprojeto_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='tipo',
            field=models.CharField(choices=[('trabalho', 'Trabalho'), ('exercicio', 'Exercício'), ('outros', 'Outros')], default='outros', max_length=20),
        ),
    ]
