# Generated by Django 6.1 on 2026-10-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_atividade_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='tipo',
            field=models.CharField(choices=[('trabalho', 'Trabalho'), ('exercicio', 'Exercício'), ('complementar', 'Atividade complementar'), ('outros', 'Outros')], default='outros', max_length=20),
        ),
    ]
